---
default:
  threads: 6
  producer_type: FutureProducer
  producer_config:
    bootstrap.servers: localhost:9092
    queue.buffering.max.ms: 100
    queue.buffering.max.messages: 1000000

scenarios:
  10B_bursts:
    repeat_times: 5
    repeat_pause: 10
    topic: benchmark_topic_10b
    message_size: 10
    message_count: 20000000

  1KB_bursts:
    repeat_times: 3
    repeat_pause: 20
    topic: benchmark_topic_1kb
    message_size: 1024
    message_count: 500000

  10KB_bursts:
    repeat_times: 3
    repeat_pause: 20
    topic: benchmark_topic_10kb
    message_size: 10240
    message_count: 50000
